vending_machine/config/routes.rb
Rails.application.routes.draw do

  root "items#index"
  
  devise_for :users

  devise_scope :user do  
     get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  resources :users
  resources :items
  resources :carts
end

  # namespace :test do
  #   resources :items
  # end

  # scope path: 'path', module: 'module', as: 'as' do
  #   resources :test
  # end

  # resources :homes do
  #   get :post, on: :collection
  # end

  # resources :homes do
  #   collection do
  #     get :post
  #     post :comment
  #   end
  # end

  # resources :homes do
  #   get :post, on: :member
  #   post :comment, on: :member
  # end

  # get  '/dashboard', to: 'dashboard#show'

vending_machine/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

vending_machine/app/models/admin.rb
class Admin < User
end

vending_machine/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

vending_machine/app/models/concerns/searchable.rb
# # models/concerns/searchable.rb

# require "elasticsearch/model"

# module Searchable

#   extend ActiveSupport::Concern

#   included do
#     include Elasticsearch::Model
#     after_commit :index_document, if: :persisted?
#     after_commit on: [:destroy] do
#       __elasticsearch__.delete_document
#     end
#   end

#   private
#   def index_document
#     __elasticsearch__.index_document
#   end
# end

vending_machine/app/models/customer.rb
class Customer < User
  
end

vending_machine/app/models/elasticsearch_data_importer.rb
# # poros/elasticsearch_data_importer.rb

#   module ElasticsearchDataImporter

#     def self.import
#       [Item].each do |model_to_search|
#         model_to_search.__elasticsearch__.create_index!(force: true)
#         model_to_search.find_in_batches do |records|
#           bulk_index(records, model_to_search)
#         end
#       end
#     end

#     def self.prepare_records(records)
#       records.map do |record|
#         {
#           index: {
#             _id: record.id,
#             data: record.__elasticsearch__.as_indexed_json
#           }
#         }
#       end
#     end

#     def self.bulk_index(records, model)
#       model.__elasticsearch__.client.bulk(
#         index: model.__elasticsearch__.index_name,
#         type: model.__elasticsearch__.document_type,
#         body: prepare_records(records)
#       )
#     end
#   end

vending_machine/app/models/item.rb
#app/models/item.rb       Item Model
require 'elasticsearch/model'

class Item < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  # include Searchable 

  belongs_to :user
  #only name as a string field
  validates :name, :price, :quantity, presence: true

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :name
      indexes :price
      indexes :quantity
    end
  end
end

vending_machine/app/models/poros/elasticsearch_data_importer.rb
# poros/elasticsearch_data_importer.rb

  module ElasticsearchDataImporter

    def self.import
      [Item].each do |model_to_search|
        model_to_search.__elasticsearch__.create_index!(force: true)
        model_to_search.find_in_batches do |records|
          bulk_index(records, model_to_search)
        end
      end
    end

    def self.prepare_records(records)
      records.map do |record|
        {
          index: {
            _id: record.id,
            data: record.__elasticsearch__.as_indexed_json
          }
        }
      end
    end

    def self.bulk_index(records, model)
      model.__elasticsearch__.client.bulk(
        index: model.__elasticsearch__.index_name,
        type: model.__elasticsearch__.document_type,
        body: prepare_records(records)
      )
    end
  end

vending_machine/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :cart, dependent: :destroy
  # enum :role, [ :admin, :customer ]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    type == 'Admin'
  end

  def customer?
    type == 'Customer'
  end
end

vending_machine/app/controllers/application_controller.rb
# app/controllers/application_controller.rb

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :type) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :mobile, :email, :password, :password_confrimation, :current_password)}
  end

  def after_sign_in_path_for(user)
    if user.type == 'Admin'
      root_path
    else
      root_path
    end
  end
end

vending_machine/app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
   @carts = Cart.where(user_id: current_user.id)
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def new
    @cart = Cart.new
  end
  
  def create
    @user = User.find(current_user.id)
    @cart = @user.cart.new(cart_params)

    redirect_to root_path, notice: "Item added into cart Successfully."
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def cart_params
    params.require(:cart).permit(:quantity)
  end
end

vending_machine/app/controllers/items_controller.rb
# app/controllers/items_controller.rb

class ItemsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @items = Item.order(price: :asc,quantity: :asc)      
    # @q = Item.ransack(params[:q])
    # @items = @q.result

    # @items = Item.search('name').records
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end
  
  def create
    @user = User.find(current_user.id)
    @item = @user.items.create(item_params)

    redirect_to root_path, notice: "#{@item.name} Added Successfully."
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to root_path, notice: "#{@item.name} Updated Successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :quantity)
  end

end

vending_machine/app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  # load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    # authorize! :read, @user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:name, :mobile)
  end
end

vending_machine/app/helpers/carts_helper.rb
module CartsHelper
  
  def self.price_by_qty(id, price)
    qty = Cart.find_by_item_id(id).quantity
    price * qty
  end

end

vending_machine/app/helpers/items_helper.rb
module ItemsHelper
  def root_path?
    request.path == "/" ? true : false
  end
end

vending_machine/app/helpers/users_helper.rb
module UsersHelper
end

vending_machine/app/views/carts/_form.html.erb
<%= form_with model: @cart do |form| %>
  <div style="margin: 20px">
    <div>
      <%= form.label :quantity %><br>
      <%= form.number_field :quantity %><br>
      <% @cart.errors.full_messages_for(:quantity).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div><br>

    <div>
      <%= form.submit "Add to cart" %>
    </div>
  </div>
<% end %>

vending_machine/app/views/carts/index.html.erb
<!-- index of carts -->

<div>
  <% unless @carts.empty? %>
    <table>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
      </tr>

      <% @carts.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= item.name %></td>
          <td><%= item.price %></td>
          <td><%= item.quantity %></td>
        </tr>
      <% end %>
  <!--     <tr>
        <td colspan="3">Total</td>
        <td><#%= CartsHelper.total_price %></td>
      </tr> -->
    </table>
  <% else %>
    <div style="margin: 10px">Your Cart is empty!!</div>
  <% end %>
</div>

vending_machine/app/views/carts/new.html.erb
<%= render "form", cart: @cart %>

vending_machine/app/views/carts/show.html.erb
<% @cart_items.each do |item| %>
  <h1><%= item.name %></h1>
<% end %>

vending_machine/app/views/items/_form.html.erb
<%= form_with model: item do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% item.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_area :price %><br>
    <% item.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :quantity %><br>
    <%= form.text_area :quantity %><br>
    <% item.errors.full_messages_for(:quantity).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

vending_machine/app/views/items/edit.html.erb
<%= render "form", item: @item %>

vending_machine/app/views/items/index.html.erb
<!-- index of items -->

<!-- <div style="margin: 10px">
  <#%= search_form_for @q, remote: true do |f| %>
    <#%= f.label :name_cont, 'Search Item' %>
    <#%= f.search_field :name_cont %>
    <#%= f.submit %>
  <#% end %>
</div> -->

<div>
  <table>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Status</th>
      <% if current_user.admin? %>
        <th>Edit</th>
        <th>Delete</th>
      <% end %>
    </tr>

    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.quantity %></td>
        <td><%= button_to "Add to cart" %></td>

        <% if current_user.admin? %>
          <td><%= button_to (image_tag ("edit.png"), height: 20), edit_item_path(item), method: :get %></td>
          <td><%= button_to (image_tag ("delete.png"), height: 20), item_path(item), method: :delete, data: {confirm: "Are you sure want delete this item?"} %></td>
        <% end %>

<!--         <td><input type="checkbox" name="buy" class="checkboxOne"></td>

        <td><input type="number" id="quantity" name="quantity" min="1" max= <%=item.quantity%>></td> -->
        
      </tr>
    <% end %>
  </table>
</div>

vending_machine/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render "form", item: @item %>

vending_machine/app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<table >
  <tr>
    <th>Price</th>
    <th>Quantity</th>
  </tr>
  <tr>
    <td><%= @item.price %></td>
    <td><%= @item.quantity %></td>
  </tr>
  <tr>
</table>

vending_machine/app/views/layouts/_navbar.html.erb
<div class="topnav">
  <%= link_to "Home", root_path %>

  <% unless root_path? %>
    <%= link_to "Back", :back %>
  <% end %>

  <div style="float: right; margin-right: 20px"> 
    <%= link_to current_user.name, user_path(current_user) %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 
    'navbar-link' %>
  </div>

  <% if root_path? %>
    <%= link_to "Add item", new_item_path(current_user) if current_user.admin? %>
    <div class="search-container">
      <form>
        <input class="searchbar" type="text" placeholder="Search" name="search">
        <button style="width: 30px; height: 30px " type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>

    <% if current_user.customer? %>
      <!-- <%#= link_to "Remove Item", new_cart_path %> -->
      <%= link_to "Cart", carts_path %>
    <% end %>
  <% end %>
</div>

vending_machine/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VendingMachine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render "layouts/navbar" %>
    <% end %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

vending_machine/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

vending_machine/app/views/users/show.html.erb
<h1><%= @user.name unless @user.name.nil?  %></h1>
<p><%= @user.email %></p>

<ul>
  <li><%= link_to "Edit your Account", edit_user_registration_path(@user) %></li><br>
  <li><%= button_to "Delete your account", user_path(@user), :method => :delete, data: {
                    turbo_confirm: "Are you sure?"
                  } %></li> 
</ul>